services:
  - type: web
    name: tripbox-static-site
    env: static
    buildCommand: echo "Static site - no build needed"
    startCommand: echo "Static site ready"
    staticPublishPath: ./frontend 