databases:
  - name: tripbox-db
    databaseName: tripbox
    user: tripbox

services:
  - type: web
    name: tripbox-prototype
    env: python
    buildCommand: |
      cd backend
      pip install flask flask-cors gunicorn
      echo "✅ Minimal build completed"
    startCommand: "cd backend && gunicorn super_minimal:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: FLASK_ENV
        value: "production" 