databases:
  - name: tripbox-db
    databaseName: tripbox
    user: tripbox

services:
  - type: web
    name: tripbox-prototype
    env: python
    buildCommand: |
      cd backend
      python --version
      pip install flask flask-cors
      echo "✅ Build completed"
    startCommand: "cd backend && python super_minimal.py"
    envVars:
      - key: FLASK_ENV
        value: "production" 