services:
  - type: web
    name: tripbox-prototype
    env: python
    buildCommand: |
      cd backend
      python --version
      pip install flask
      echo "✅ Emergency build completed"
    startCommand: "cd backend && python emergency_minimal.py" 