# Force update
name: Backend CI/CD


on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Backend Unit Tests
        run: |
          cd backend
          python -m unittest discover

      - name: Trigger Render Deployment
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1nvfm7diees73b9nid0?key=K4LH9OMRWnY