name: Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install flask flask-cors

      - name: Test Import
        run: |
          cd backend
          python -c "print('Testing basic imports...'); import flask; print('✅ Flask imports successfully')"

      - name: Run Health Check
        run: |
          cd backend
          python -c "print('✅ Backend setup completed')"

      - name: Trigger Render Deployment
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deployment would be triggered here"
